# -*- coding: utf-8 -*-
"""Task01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tg8C5eDKUp8Nb4IJQBfL_7RhQb1Fznt5
"""

import  pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from  sklearn.metrics import mean_squared_error, r2_score

import matplotlib.pyplot as plt

ds=pd.read_csv("train.csv")

ds

features = ["GrLivArea","BedroomAbvGr", "FullBath"]

x = ds[features]

y = ds["SalePrice"]

x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=40)

model = LinearRegression()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)

r2= r2_score(y_test,y_pred)

print(f'Mean Squared Error:{mse}')
print(f'R_squared Error:{r2}')

plt.scatter(y_test,y_pred)
plt.xlabel("Actual Price ")
plt.ylabel("Predicted Price")
plt.title("Actual Price vs Predicted Price")
plt.show()

new_data =pd.DataFrame({'GrLivArea':[2000],'BedroomAbvGr':[3],'FullBath':[2]})
predicted_price = model.predict(new_data)
print(f'Predicted Price:{predicted_price[0]}')